### ISSUE TITLE
Requires non-free software to build ? not true - IAR STM8 Free for 8K

### ISSUE THREAD

**Issue by spth** [wassfila/STM8_IoT_HelloWorld#1]
From the wiki:
"Our answer approach Open Products = Open Hardware + Open Software"

But the software here only comes with projects for non-free IAR. How about adding Makefiles for free SDCC?

Philipp

**Comment by wassfila** [comment]
Hi,
thank you for your comment, that is very helpful.
My approach is not to be dependent of any non-free SW, and that on the long
run.
As explained in my wiki, That special version of IAR Studio is free for non
commerical with full STM8S memory usage. I admit, a registration is
required.
IAR is not just a compiler, but also flasher, debugger, simulator. If
possible to have both IAR and SDCC, that would be cool.

http://www.homesmartmesh.com/mediawiki/index.php/IoT_Node#Development_Tools

I'm still evaluating different compilers and considering including them, so
if you have any links to simple introduction or examples using sdcc, let me
know, otherwise, I'll also keep looking myself.
I think for any one already working with sdcc, the source code provided
here is still rather helpful. License allows copy paste.

Wassim

**Comment by spth** [comment]
A comparison of C compilers for the STM8 can be found here:
http://colecovision.eu/stm8/compilers.shtml
I also wrote a few tutorials for STM8 development using SDCC:
http://www.colecovision.eu/stm8/

Philipp

**Comment by wassfila** [comment]
SDCC is very good alternative to get rid of memory limitation for bigger devices, and is planned to be developped. But as the IAR has a free unlimited in time, but limited with 8K memory which fits to the STM8S103F3 devices, this issue is considered as closed.
