### ISSUE TITLE
Error in array definition

### ISSUE THREAD

**Issue by denruss** [wassfila/STM8_IoT_HelloWorld#3]
maybe? unsigned char LedsArray[NB_LEDS] -> unsigned char LedsArray[NB_LEDS*3];

**Comment by wassfila** [comment]
Hi, thanks for reporting this issue, this was indeed found and fixed [here](https://github.com/HomeSmartMesh/IoT_STM8/blob/master/libs/WS2812B.c) in a further repository where this code has been moved.
I feel sorry that you had to debug a code that is not maintained, deprecated and where another code location has been fixed, I documented that now on the readme with this commit 3a7ca95.
That code was also my beginning with bigger projects integration, which was a mess in terms of code duplication (copy paste lib in every directory), I since started using submodules for other libraries (STM32, rpi), which does not make it simpler, but at least cleaner and avoids such confusion.
This [code here](https://github.com/HomeSmartMesh/IoT_STM8/tree/master/firmware_rf_sensors_node/pr03_PressHumTemp),  is what currently used on the field. I have five STM8L nodes continuously logging sensors for more than a year now. The dongle has been replaced with an STM32 versions, and sensors are getting replaced with nRF51 Sensors tags.
So if you have further questions or issues, just let me know.
